inherit_from:
  - /Users/jaren/node_modules/@prettier/plugin-ruby/rubocop.yml
require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-thread_safety
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
