require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-require_tools
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-sorbet
  - rubocop-thread_safety
RSpec/ExampleLength:
  Enabled: false
Naming/FileName:
  Exclude:
    - Gemfile
AllCops:
  NewCops: enable
  Include:
    - "sorbet/rbi/shims/**/*.rbi"
  ParserEngine: parser_prism
  TargetRubyVersion: 3.3
