# frozen_string_literal: true

source 'https://rubygems.org'

gem 'prettier_print'
gem 'pry'
gem 'pry-byebug'
gem 'rails'
gem 'rspec'
gem 'rubocop', require: false
gem 'rubocop-performance', require: false
gem 'rubocop-rspec', require: false
gem 'rubocop-thread_safety', require: false
gem 'ruby-lsp', require: false
gem "ruby-lsp-rspec", require: false
gem 'syntax_tree'
gem 'syntax_tree-haml'
gem 'syntax_tree-rbs'
