# frozen_string_literal: true

source 'https://rubygems.org'

gem 'pry'
gem 'pry-byebug'
gem 'rspec'
gem 'rubocop', require: false
gem 'rubocop-performance', require: false
gem 'rubocop-rspec', require: false
