# frozen_string_literal: true

source 'https://rubygems.org'

gem 'pry'
gem 'pry-byebug'
gem 'rails'
gem 'rspec'
gem 'rubocop', require: false
gem 'rubocop-performance', require: false
gem 'rubocop-rails', require: false
gem 'rubocop-rake', require: false
gem 'rubocop-require_tools', require: false
gem 'rubocop-rspec', require: false
gem 'rubocop-rspec_rails', require: false
